<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IND-CHN-LT12488" failures="1" tests="1" name="DataTest" time="23.47" errors="0" timestamp="2025-01-27T03:08:45 IST">
  <testcase classname="TestCase.TC003LogInTestDDT" name="Verify_logInDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at Utilities.DataProviders.getData(DataProviders.java:23)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Verify_logInDDT -->
</testsuite> <!-- DataTest -->
